/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_browsernode_free: (a: number, b: number) => void;
export const __wbg_cancelhandle_free: (a: number, b: number) => void;
export const browsernode_add_file: (a: number, b: number, c: number, d: number, e: any, f: any, g: any) => any;
export const browsernode_cancel_handle: (a: number) => number;
export const browsernode_close: (a: number) => any;
export const browsernode_decline: (a: number) => any;
export const browsernode_inspect: (a: number, b: number, c: number) => any;
export const browsernode_qr_svg: (a: number, b: number, c: number) => [number, number, number, number];
export const browsernode_receive: (a: number, b: number, c: number, d: any, e: any) => any;
export const browsernode_share: (a: number) => any;
export const browsernode_spawn: (a: number, b: number) => any;
export const browsernode_status: (a: number) => [number, number];
export const cancelhandle_cancel: (a: number) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h426a2ac9f014f57a: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h375a1c12e1a64648: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hd2dbeb3ab97b5c58: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h40aef191e4148fbd: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hff3f3f26b5a708dd: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2727bd29ffa19b04: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hd800e0d20381508d: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h598255fb780a24c6: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h283edd717a05bb96: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
